tasks:
  - init: |
      curl -Ls https://github.com/prefix-dev/pixi/releases/download/v0.30.0/pixi-x86_64-unknown-linux-musl -o /usr/local/bin/pixi
      chmod +x /usr/local/bin/pixi
      wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.5.57/quarto-1.5.57-linux-arm64.tar.gz
      tar -xvzf quarto-1.5.57-linux-arm64.tar.gz
      mkdir -p $HOME/bin
      mv quarto-1.5.57/bin/quarto $HOME/bin/
      export PATH="$HOME/bin:$PATH"
      rm quarto-1.5.57-linux-arm64.tar.gz
