name: base

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python=3.10
  - conda-forge::r-base==4.3.2
  - conda-forge::r-rmarkdown==2.25
  - conda-forge::r-tidyverse==2.0.0
  - conda-forge::r-palmerpenguins==0.1.1