[project]
name = "post"
version = "0.1.0"
description = "Add a short description here"
channels = ["conda-forge", "bioconda", "anaconda"]
platforms = ["linux-64"]

[tasks]

[dependencies]
quarto = "==1.4.550"
r-base = "4.3.*"
r-ggplot2 = "==3.4.4"
r-rmarkdown = ""
r-knitr = ""
bioconductor-mzr = "==2.36.0"
r-codetools = ""
r-plotly = ""
